spring:
  datasource:
    url: jdbc:h2:file:/home/adrien/Documents/tp4-spingboot-efrei-atr/tests/db/contacts.mv.db
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true